// graph-visualizer/web/src/components/GraphFlow.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import ReactFlow, {
  Controls,
  Background,
  MiniMap,
  useNodesState,
  useEdgesState,
  type Node,
  type Edge,
  type NodeDragHandler,
  type OnSelectionChangeFunc,
  type NodeTypes,
} from 'reactflow';
import 'reactflow/dist/style.css';
import dagre from 'dagre';
import { fetchGraph, fetchPositions, savePositions } from '../api';
import type { DependencyGraph, DependencyNode, NodePosition } from '../types';
import NodeBox from './NodeBox';
import FileBrowser from './FileBrowser';

const nodeTypes: NodeTypes = {
  dependency: NodeBox,
};

export default function GraphFlow() {
  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [, setSelectedNodeId] = useState<string | null>(null);
  const [selectedNode, setSelectedNode] = useState<DependencyNode | null>(null);
  const [showFileBrowser, setShowFileBrowser] = useState(false);
  const [graph, setGraph] = useState<DependencyGraph | null>(null);
  const saveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const handleFileBrowser = useCallback((nodeId: string) => {
    setSelectedNodeId(nodeId);
    const node = graph?.nodes.find(n => n.id === nodeId) || null;
    setSelectedNode(node);
    setShowFileBrowser(true);
    updateNodeSelection(nodeId);
    updateNodesFileBrowserState(nodeId, true);
  }, [graph]);

  const updateNodesFileBrowserState = useCallback((nodeId: string | null, show: boolean) => {
    setNodes(nodes => nodes.map(node => ({
      ...node,
      data: {
        ...node.data,
        isViewingFiles: show && node.id === nodeId
      }
    })));
  }, [setNodes]);

  const updateNodeSelection = useCallback((nodeId: string | null) => {
    if (!graph) return;
    
    setNodes(nodes => nodes.map(node => ({
      ...node,
      selected: node.id === nodeId,
      style: {
        ...node.style,
        opacity: nodeId ? (node.id === nodeId ? 1 : 0.5) : 1,
      }
    })));

    // Update edge highlighting
    if (nodeId) {
      const node = graph.nodes.find(n => n.id === nodeId);
      if (!node) return;

      const parentEdges = new Set(
        graph.edges
          .filter(e => e.target === nodeId)
          .map(e => e.id)
      );
      
      const childEdges = new Set(
        graph.edges
          .filter(e => e.source === nodeId)
          .map(e => e.id)
      );

      setEdges(edges => edges.map(edge => {
        let edgeClass = '';
        if (parentEdges.has(edge.id)) {
          edgeClass = 'parent-edge';
        } else if (childEdges.has(edge.id)) {
          edgeClass = 'child-edge';
        }
        
        return { 
          ...edge, 
          className: edgeClass,
          animated: edge.source === nodeId || edge.target === nodeId 
        };
      }));
    } else {
      // Reset all edges to default style
      setEdges(edges => edges.map(edge => ({
        ...edge,
        className: '',
        animated: false
      })));
    }
  }, [graph, setNodes, setEdges]);

  const onSelectionChange: OnSelectionChangeFunc = useCallback(({ nodes }) => {
    if (nodes.length > 0) {
      const nodeId = nodes[0].id;
      setSelectedNodeId(nodeId);
      updateNodeSelection(nodeId);
    } else {
      setSelectedNodeId(null);
      updateNodeSelection(null);
    }
  }, [updateNodeSelection]);

  const closeFileBrowser = useCallback(() => {
    setShowFileBrowser(false);
    setSelectedNode(null);
    updateNodeSelection(null);
    updateNodesFileBrowserState(null, false);
  }, [updateNodeSelection, updateNodesFileBrowserState]);

  const layoutNodes = useCallback((graphData: DependencyGraph, savedPositions: NodePosition[]) => {
    const dagreGraph = new dagre.graphlib.Graph();
    dagreGraph.setDefaultEdgeLabel(() => ({}));
    dagreGraph.setGraph({ rankdir: 'TB', ranksep: 100, nodesep: 80 });

    const positionMap = new Map(Array.isArray(savedPositions) ? savedPositions.map(p => [p.nodeId, p]) : []);

    // Create nodes
    const newNodes: Node[] = graphData.nodes.map(node => {
      const savedPosition = positionMap.get(node.id);
      
      if (savedPosition) {
        return {
          id: node.id,
          type: 'dependency',
          position: { x: savedPosition.x, y: savedPosition.y },
          data: { ...node, onFileBrowser: handleFileBrowser },
        };
      } else {
        dagreGraph.setNode(node.id, { width: 200, height: 100 });
        return {
          id: node.id,
          type: 'dependency',
          position: { x: 0, y: 0 },
          data: { ...node, onFileBrowser: handleFileBrowser },
        };
      }
    });

    // Add edges to dagre
    graphData.edges.forEach(edge => {
      dagreGraph.setEdge(edge.source, edge.target);
    });

    // Calculate layout only for nodes without saved positions
    if (!savedPositions || savedPositions.length < graphData.nodes.length) {
      dagre.layout(dagreGraph);
      
      newNodes.forEach(node => {
        if (!positionMap.has(node.id)) {
          const nodeWithPosition = dagreGraph.node(node.id);
          node.position = {
            x: nodeWithPosition.x - 100,
            y: nodeWithPosition.y - 50,
          };
        }
      });
    }

    // Create edges
    const newEdges: Edge[] = graphData.edges.map(edge => ({
      id: edge.id,
      source: edge.source,
      target: edge.target,
      type: 'default',
    }));

    setNodes(newNodes);
    setEdges(newEdges);
  }, [handleFileBrowser, setNodes, setEdges]);

  const handleNodeDragStop: NodeDragHandler = useCallback(() => {
    // Debounce position saves
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }
    
    saveTimeoutRef.current = setTimeout(async () => {
      // Collect all node positions
      const positions = nodes.map(node => ({
        nodeId: node.id,
        x: node.position.x,
        y: node.position.y
      }));
      
      try {
        await savePositions(positions);
      } catch (err) {
        console.error('Failed to save positions:', err);
      }
    }, 500);
  }, [nodes]);

  useEffect(() => {
    async function loadData() {
      try {
        const [graphData, positions] = await Promise.all([
          fetchGraph(),
          fetchPositions()
        ]);
        
        setGraph(graphData);
        layoutNodes(graphData, positions);
        setLoading(false);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load graph');
        setLoading(false);
      }
    }

    loadData();
  }, [layoutNodes]);

  if (loading) {
    return <div className="loading-container">Loading graph...</div>;
  }

  if (error) {
    return <div className="error-container">Error: {error}</div>;
  }

  return (
    <div className={`app-container ${showFileBrowser ? 'split' : ''}`}>
      <div className="graph-container">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onSelectionChange={onSelectionChange}
          onNodeDragStop={handleNodeDragStop}
          nodeTypes={nodeTypes}
          fitView
          fitViewOptions={{ padding: 0.2 }}
        >
          <Background />
          <Controls />
          <MiniMap 
            style={{ background: '#f5f5f5', border: '1px solid #ddd' }}
            nodeColor="#69b3a2"
          />
        </ReactFlow>
      </div>
      
      {showFileBrowser && (
        <div className="browser-container">
          <FileBrowser node={selectedNode} onClose={closeFileBrowser} />
        </div>
      )}
    </div>
  );
}

// graph-visualizer/web/src/lib/GraphFlow.svelte
<script lang="ts">
  import { SvelteFlow, Background, Controls, MiniMap } from '@xyflow/svelte';
  import '@xyflow/svelte/dist/style.css';
  import { onMount } from 'svelte';
  import type { Node, Edge } from '@xyflow/svelte';
  import type { DependencyGraph, DependencyNode } from '../types';
  import { fetchGraph, fetchPositions, savePositions } from './api';
  import NodeBox from './NodeBox.svelte';
  import FileBrowser from './FileBrowser.svelte';
  import dagre from 'dagre';
  
  let nodes = $state.raw<Node[]>([]);
  let edges = $state.raw<Edge[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let selectedNodeId = $state<string | null>(null);
  let selectedNode = $state<DependencyNode | null>(null);
  let showFileBrowser = $state(false);
  let graph = $state<DependencyGraph | null>(null);
  let flowKey = $state(0);
  let saveTimeout: NodeJS.Timeout | null = null;
  
  const nodeTypes = {
    dependency: NodeBox
  };
  
  function handleFileBrowser(nodeId: string) {
    selectedNodeId = nodeId;
    selectedNode = graph?.nodes.find(n => n.id === nodeId) || null;
    showFileBrowser = true;
    updateNodeSelection(nodeId);
    // Update nodes to show file browser state
    updateNodesFileBrowserState();
  }
  
  function updateNodesFileBrowserState() {
    nodes = nodes.map(node => ({
      ...node,
      data: {
        ...node.data,
        isViewingFiles: showFileBrowser && node.id === selectedNodeId
      }
    }));
  }
  
  function handleNodeClick(params: { node: Node; event: MouseEvent }) {
    const nodeId = params.node.id;
    selectedNodeId = nodeId;
    updateNodeSelection(nodeId);
  }
  
  function updateNodeSelection(nodeId: string | null) {
    if (!graph) return;
    
    // Update node data to include selection state
    nodes = nodes.map(node => ({
      ...node,
      data: {
        ...node.data,
        onFileBrowser: handleFileBrowser,
        isViewingFiles: showFileBrowser && node.id === selectedNodeId
      },
      selected: node.id === nodeId
    }));
    
    // Update edge styles based on selection
    if (nodeId) {
      const parentEdges = new Set<string>();
      const childEdges = new Set<string>();
      
      edges.forEach((edge) => {
        if (edge.target === nodeId) {
          parentEdges.add(edge.id);
        } else if (edge.source === nodeId) {
          childEdges.add(edge.id);
        }
      });
      
      // Create new edges array to ensure reactivity
      const newEdges = edges.map((edge) => {
        let edgeClass = '';
        
        if (parentEdges.has(edge.id)) {
          edgeClass = 'parent-edge'; // Green for parents
        } else if (childEdges.has(edge.id)) {
          edgeClass = 'child-edge'; // Blue for children
        }
        
        return { 
          ...edge, 
          class: edgeClass,
          animated: edge.source === nodeId || edge.target === nodeId 
        };
      });
      
      edges = [...newEdges];
    } else {
      // Reset all edges to default style
      edges = edges.map(edge => ({
        ...edge,
        class: '',
        animated: false
      }));
    }
  }
  
  function layoutGraph(graphData: DependencyGraph): { nodes: Node[], edges: Edge[] } {
    const dagreGraph = new dagre.graphlib.Graph();
    dagreGraph.setDefaultEdgeLabel(() => ({}));
    dagreGraph.setGraph({ 
      rankdir: 'TB',
      ranksep: 80,
      nodesep: 50,
      marginx: 50,
      marginy: 50
    });
    
    // Add nodes to dagre
    graphData.nodes.forEach((node) => {
      dagreGraph.setNode(node.id, { width: 200, height: 100 });
    });
    
    // Add edges to dagre
    graphData.edges.forEach((edge) => {
      dagreGraph.setEdge(edge.source, edge.target);
    });
    
    // Calculate layout
    dagre.layout(dagreGraph);
    
    // Convert to SvelteFlow nodes
    const layoutNodes: Node[] = graphData.nodes.map((node) => {
      const nodeWithPosition = dagreGraph.node(node.id);
      return {
        id: node.id,
        type: 'dependency',
        data: { 
          node,
          onFileBrowser: handleFileBrowser,
          isViewingFiles: showFileBrowser && node.id === selectedNodeId
        },
        position: {
          x: nodeWithPosition.x - nodeWithPosition.width / 2,
          y: nodeWithPosition.y - nodeWithPosition.height / 2
        }
      };
    });
    
    // Convert to SvelteFlow edges
    const layoutEdges: Edge[] = graphData.edges.map((edge, index) => ({
      id: `e${index}`,
      source: edge.source,
      target: edge.target,
      type: 'smoothstep',
      animated: false,
      class: ''
    }));
    
    return { nodes: layoutNodes, edges: layoutEdges };
  }
  
  onMount(async () => {
    try {
      const graphData = await fetchGraph();
      graph = graphData;
      const layout = layoutGraph(graphData);
      nodes = layout.nodes;
      edges = layout.edges;
      
      // Load saved positions
      try {
        const savedPositions = await fetchPositions();
        
        // Apply saved positions to nodes
        nodes = nodes.map(node => {
          const savedPos = savedPositions[node.id];
          if (savedPos) {
            return {
              ...node,
              position: {
                x: savedPos.x,
                y: savedPos.y
              }
            };
          }
          return node;
        });
      } catch (err) {
        console.warn('No saved positions or error loading them:', err);
      }
      
      loading = false;
    } catch (err) {
      error = err instanceof Error ? err.message : 'Unknown error';
      loading = false;
    }
  });
  
  function closeFileBrowser() {
    showFileBrowser = false;
    selectedNodeId = null;
    selectedNode = null;
    updateNodeSelection(null);
    updateNodesFileBrowserState();
  }
  
  function handleNodeDragStop(params: { node: Node; event: MouseEvent }) {
    // Debounce position saves
    if (saveTimeout) {
      clearTimeout(saveTimeout);
    }
    
    saveTimeout = setTimeout(async () => {
      // Collect all node positions
      const positions = nodes.map(node => ({
        nodeId: node.id,
        x: node.position.x,
        y: node.position.y
      }));
      
      try {
        await savePositions(positions);
      } catch (err) {
        console.error('Failed to save positions:', err);
      }
    }, 500); // Save after 500ms of no dragging
  }
</script>

<div class="app-container" class:split={showFileBrowser}>
  <div class="graph-container">
    {#if loading}
      <div class="loading">Loading graph...</div>
    {:else if error}
      <div class="error">Error: {error}</div>
    {:else}
      <SvelteFlow 
        bind:nodes
        bind:edges
        {nodeTypes}
        fitView
        fitViewOptions={{ padding: 0.2 }}
        onnodeclick={handleNodeClick}
        onnodedragstop={handleNodeDragStop}
      >
        <Background />
        <Controls />
        <MiniMap 
          style="background: #f5f5f5; border: 1px solid #ddd;"
          nodeColor="#69b3a2"
        />
      </SvelteFlow>
    {/if}
  </div>
  
  {#if showFileBrowser}
    <div class="browser-container">
      <FileBrowser node={selectedNode} onClose={closeFileBrowser} />
    </div>
  {/if}
</div>

<style>
  .app-container {
    display: flex;
    width: 100vw;
    height: 100vh;
    overflow: hidden;
  }
  
  .graph-container {
    flex: 1;
    height: 100vh;
    background: #f5f5f5;
    transition: all 0.3s ease;
  }
  
  .app-container.split .graph-container {
    width: 60%;
  }
  
  .browser-container {
    width: 40%;
    height: 100vh;
    border-left: 1px solid #ddd;
    background: white;
    overflow: hidden;
    animation: slideIn 0.3s ease;
  }
  
  @keyframes slideIn {
    from {
      transform: translateX(100%);
    }
    to {
      transform: translateX(0);
    }
  }
  
  .loading, .error {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-size: 18px;
  }
  
  .error {
    color: #d32f2f;
  }
  
  :global(.parent-edge .svelte-flow__edge-path) {
    stroke: #4CAF50 !important;
    stroke-width: 3 !important;
  }
  
  :global(.child-edge .svelte-flow__edge-path) {
    stroke: #2196F3 !important;
    stroke-width: 3 !important;
  }
  
  :global(.svelte-flow__edge-path) {
    stroke: #999;
    stroke-width: 2;
  }
</style>
