// graph-visualizer/web/src/lib/NodeBox.svelte
<script lang="ts">
  import { Handle, Position } from '@xyflow/svelte';
  import type { DependencyNode } from '../types';
  
  interface Props {
    data: {
      node: DependencyNode;
      onFileBrowser?: (nodeId: string) => void;
    };
    selected?: boolean;
  }
  
  const { data, selected = false }: Props = $props();
  
  function handleFileBrowser() {
    data.onFileBrowser?.(data.node.id);
  }
</script>

<div class="node-box" class:selected>
  <Handle type="target" position={Position.Top} />
  
  <div class="node-header">
    <div class="node-title">{data.node.name}</div>
    <div class="node-actions">
      <button class="action-btn" onclick={handleFileBrowser} title="Browse files" aria-label="Browse files">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
        </svg>
      </button>
    </div>
  </div>
  
  <div class="node-content">
    <div class="node-path">{data.node.path}</div>
    {#if data.node.dependencies.length > 0}
      <div class="node-deps">
        <small>Dependencies: {data.node.dependencies.length}</small>
      </div>
    {/if}
  </div>
  
  <Handle type="source" position={Position.Bottom} />
</div>

<style>
  .node-box {
    background: white;
    border: 2px solid #69b3a2;
    border-radius: 8px;
    width: 200px;
    min-height: 80px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    transition: all 0.2s ease;
  }
  
  .node-box.selected {
    border-color: #ff6b6b;
    box-shadow: 0 4px 16px rgba(255, 107, 107, 0.3);
  }
  
  .node-header {
    background: #69b3a2;
    color: white;
    padding: 8px 12px;
    font-weight: bold;
    font-size: 14px;
    border-radius: 6px 6px 0 0;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .node-box.selected .node-header {
    background: #ff6b6b;
  }
  
  .node-title {
    flex: 1;
    text-align: center;
  }
  
  .node-actions {
    display: flex;
    gap: 4px;
  }
  
  .action-btn {
    background: none;
    border: none;
    color: white;
    cursor: pointer;
    padding: 2px;
    border-radius: 4px;
    transition: background 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .action-btn:hover {
    background: rgba(255, 255, 255, 0.2);
  }
  
  .node-content {
    padding: 12px;
  }
  
  .node-path {
    font-size: 12px;
    color: #666;
    margin-bottom: 8px;
  }
  
  .node-deps {
    font-size: 11px;
    color: #999;
  }
  
  :global(.svelte-flow__handle) {
    background: #69b3a2;
    width: 8px;
    height: 8px;
  }
</style>

// graph-visualizer/web/src/components/NodeBox.tsx
import React from 'react';
import { Handle, Position, type NodeProps } from 'reactflow';
import type { DependencyNode } from '../types';

interface NodeData extends DependencyNode {
  onFileBrowser: (nodeId: string) => void;
  isViewingFiles?: boolean;
}

export default function NodeBox({ data, selected }: NodeProps<NodeData>) {
  const handleFileBrowser = (e: React.MouseEvent) => {
    e.stopPropagation();
    data.onFileBrowser(data.id);
  };

  return (
    <div className={`node-box ${data.type === 'module' ? 'is-module' : ''} ${selected ? 'selected' : ''} ${data.isViewingFiles ? 'viewing-files' : ''}`}>
      <Handle type="target" position={Position.Top} />
      
      <div className="node-header">
        <h4>{data.name}</h4>
        <div className="node-actions">
          <button 
            className="action-btn" 
            onClick={handleFileBrowser}
            title="Browse files"
            aria-label="Browse files"
          >
            📁
          </button>
        </div>
      </div>
      
      <div className="node-info">
        <div className="info-item">
          <span className="label">Type:</span>
          <span className="value">{data.type}</span>
        </div>
        {data.dependencies.length > 0 && (
          <div className="info-item">
            <span className="label">Dependencies:</span>
            <span className="value">{data.dependencies.length}</span>
          </div>
        )}
      </div>
      
      <Handle type="source" position={Position.Bottom} />
    </div>
  );
}
